# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef51/setup-makefiles.sh

#IM-A860L
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51l/vidcfw.elf:system/etc/firmware_ef51l/vidcfw.elf \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51l/vidc.mdt:system/etc/firmware_ef51l/vidc.mdt \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51l/vidc.b00:system/etc/firmware_ef51l/vidc.b00 \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51l/vidc.b01:system/etc/firmware_ef51l/vidc.b01 

#IM-A860S
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51s/vidcfw.elf:system/etc/firmware_ef51s/vidcfw.elf \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51s/vidc.mdt:system/etc/firmware_ef51s/vidc.mdt \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51s/vidc.b00:system/etc/firmware_ef51s/vidc.b00 \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51s/vidc.b01:system/etc/firmware_ef51s/vidc.b01 

#IM-A860K
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51k/vidcfw.elf:system/etc/firmware_ef51k/vidcfw.elf \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51k/vidc.mdt:system/etc/firmware_ef51k/vidc.mdt \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51k/vidc.b00:system/etc/firmware_ef51k/vidc.b00 \
    vendor/pantech/ef51/proprietary/etc/firmware_ef51k/vidc.b01:system/etc/firmware_ef51k/vidc.b01 

PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/pantech/ef51/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/pantech/ef51/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/pantech/ef51/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/pantech/ef51/proprietary/lib/hw/sensors_native_hal.so:system/lib/hw/sensors_native_hal.so \
    vendor/pantech/ef51/proprietary/lib/hw/sensors_qcom.so:system/lib/hw/sensors_qcom.so \
    #vendor/pantech/ef51/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so

PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/pantech/ef51/proprietary/etc/firmwarea225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/pantech/ef51/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/pantech/ef51/proprietary/etc/firmware/cyttsp_8064_mtp.hex:system/etc/firmware/cyttsp_8064_mtp.hex \
    vendor/pantech/ef51/proprietary/etc/firmware/cyttsp_8960_cdp.hex:system/etc/firmware/cyttsp_8960_cdp.hex \
    vendor/pantech/ef51/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/pantech/ef51/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/pantech/ef51/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/pantech/ef51/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/pantech/ef51/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/pantech/ef51/proprietary/etc/firmware/libpn544_fw.so:system/etc/firmware/libpn544_fw.so \
