# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/msm8960-common/setup-makefiles.sh

#Detect different device to fix camera
ifeq ($(filter ef50l ef48s ef49k,$(TARGET_DEVICE)),)
PRODUCT_COPY_FILES += \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon
endif

#GPU firmware
PRODUCT_COPY_FILES += \
    vendor/pantech/msm8960-common/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/pantech/msm8960-common/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw

PRODUCT_COPY_FILES += \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/diag_klog:$(TARGET_COPY_OUT_VENDOR)/bin/diag_klog \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/diag_mdlog:$(TARGET_COPY_OUT_VENDOR)/bin/diag_mdlog \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/loc_launcher:$(TARGET_COPY_OUT_VENDOR)/bin/loc_launcher \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/hci_qcomm_init:$(TARGET_COPY_OUT_VENDOR)/bin/hci_qcomm_init \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/irsc_util:$(TARGET_COPY_OUT_VENDOR)/bin/irsc_util \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/ks:$(TARGET_COPY_OUT_VENDOR)/bin/ks \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/port-bridge:$(TARGET_COPY_OUT_VENDOR)/bin/port-bridge \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/mpdecision:$(TARGET_COPY_OUT_VENDOR)/bin/mpdecision \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/qcks:$(TARGET_COPY_OUT_VENDOR)/bin/qcks \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/qmiproxy:$(TARGET_COPY_OUT_VENDOR)/bin/qmiproxy \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/radish:$(TARGET_COPY_OUT_VENDOR)/bin/radish \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/thermald:$(TARGET_COPY_OUT_VENDOR)/bin/thermald \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/bridgemgrd:$(TARGET_COPY_OUT_VENDOR)/bin/bridgemgrd \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/btnvtool:$(TARGET_COPY_OUT_VENDOR)/bin/btnvtool \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/fetch-swv:$(TARGET_COPY_OUT_VENDOR)/bin/fetch-swv \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/cnd:$(TARGET_COPY_OUT_VENDOR)/bin/cnd \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/ds_fmc_appd:$(TARGET_COPY_OUT_VENDOR)/bin/ds_fmc_appd \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/efsks:$(TARGET_COPY_OUT_VENDOR)/bin/efsks \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/qrngd:$(TARGET_COPY_OUT_VENDOR)/bin/qrngd \
    vendor/pantech/msm8960-common/proprietary/vendor/bin/sensorservice:$(TARGET_COPY_OUT_VENDOR)/bin/sensorservice \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsprpc.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneapiclient.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libcneqmiutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneqmiutils.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libcneutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneutils.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libCommandSvc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCommandSvc.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libconfigdb.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libcsd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcsd-client.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libdrmdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmdiag.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmfs.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmtime.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libdss.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdss.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libExtendedExtractor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libExtendedExtractor.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libgemini.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgemini.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libgnustl_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgnustl_shared.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libfactoryutil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfactoryutil.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libimage-jpeg-enc-omx-comp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libimage-omx-common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimage-omx-common.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmercury.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmercury.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmm-abl-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-abl-oem.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmm-abl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-abl.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmm-color-convertor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-color-convertor.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmm-color-convertor_jb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-color-convertor_jb.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg_interface.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmmjps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjps.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmmmpo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmmpo.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmmmpod.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmmpod.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmmparser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmparser.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmmrtpencoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmrtpencoder.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmmstillomx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmstillomx.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmorpho_easy_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_easy_hdr.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libNimsWrap.so:$(TARGET_COPY_OUT_VENDOR)/lib/libNimsWrap.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libOlaEngine.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOlaEngine.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqcci_adc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_adc.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqctdspsreg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqctdspsreg.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqctdspstest.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqctdspstest.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmi_csvt_srvc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csvt_srvc.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/librmp.so:$(TARGET_COPY_OUT_VENDOR)/lib/librmp.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libVDFaceAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libVDFaceAPI.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libWVphoneAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVphoneAPI.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libdiagdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiagdpl.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libloc_adapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_adapter.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libloc_api_v02.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_api_v02.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libloc_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_core.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libloc_eng.so:$(TARGET_COPY_OUT_VENDOR)/lib/libloc_eng.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libgps.utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgps.utils.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmissa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmissa.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libualutil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libualutil.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/hw/gps.msm8960.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.msm8960.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/hw/nfc.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/nfc.default.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/liboem_ssa.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboem_ssa.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libvendor_aka.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvendor_aka.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libyas530.so:$(TARGET_COPY_OUT_VENDOR)/lib/libyas530.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglsubAndroid.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmwvmplugin.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L1.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L1.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libc2d30.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libWVphoneAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVphoneAPI.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libbt-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-vendor.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libbtnv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbtnv.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libc2d2_a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d2_a3xx.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a3xx.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libc2d2_z180.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d2_z180.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libepdsp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libepdsp.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgeofence.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libizat_core.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgeofence.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/liblbs_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblbs_core.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/liblocationservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblocationservice.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libllvm-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-a3xx.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libllvm-arm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-arm.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/liblowi_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblowi_client.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libmsapm_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmsapm_jni.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqc-opt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqc-opt.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libquipc_os_api.so:$(TARGET_COPY_OUT_VENDOR)/lib/libquipc_os_api.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libquipc_ulp_adapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libquipc_ulp_adapter.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libsc-a2xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a2xx.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libsc-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a3xx.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libulp2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libulp2.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvm.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib/librpmb.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssd.so \
